// script/seed-vetusta.ts
import { seedDb as db } from '../seed-config';
import { people } from '../schema';

export async function seedPeople() {
  try {
    console.log('🏗️ Starting people table seeding...');

const peopleData = [
  {
    firstname: 'Ilaria',
    lastname: 'Magrin',
    email: 'ilaria.magrin@arsenalia.com',
    level: 'L7',
    role: 'Management',
    team: 'Management',
  },
  {
    firstname: 'Filippo',
    lastname: 'Stocco',
    email: 'filippo.stocco@arsenalia.com',
    level: 'L5',
    role: 'Account',
    team: 'Account',
  },
  {
    firstname: 'Giorgia',
    lastname: 'Manfreo',
    email: 'giorgia.manfreo@arsenalia.com',
    level: 'L4',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Carlo',
    lastname: 'Albertini',
    email: 'carlo.albertini@arsenalia.com',
    level: 'L5',
    role: 'Dir. Creativa',
    team: 'Dir. Creativa',
  },
  {
    firstname: 'Martina',
    lastname: 'Cognolato',
    email: 'martina.cognolato@arsenalia.com',
    level: 'L5',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Ivan',
    lastname: 'Dal Cin',
    email: 'ivan.dalcin@arsenalia.com',
    level: 'L3',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Giorgia',
    lastname: 'Roccabella',
    email: 'giorgia.roccabella@arsenalia.com',
    level: 'L2',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Francesca',
    lastname: 'Carrer',
    email: 'francesca.carrer@arsenalia.com',
    level: 'L3',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Riccardo',
    lastname: 'Marchiori',
    email: 'riccardo.marchiori@arsenalia.com',
    level: 'L2',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Enrico',
    lastname: 'Biasibetti',
    email: 'enrico.biasibetti@arsenalia.com',
    level: 'L8',
    role: 'Sales',
    team: 'Sales',
  },
  {
    firstname: 'Silvia',
    lastname: 'Chinello',
    email: 'silvia.chinello@arsenalia.com',
    level: 'L2',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Gabriele',
    lastname: 'Zampieri',
    email: 'gabriele.zampieri@arsenalia.com',
    level: 'L2',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Isabella Angela',
    lastname: 'Brendolin',
    email: 'isabellaangela.brendolin@arsenalia.com',
    level: 'L2',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Alice',
    lastname: 'Aiardi',
    email: 'alice.aiardi@arsenalia.com',
    level: 'L3',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Marco',
    lastname: 'Ranaldi',
    email: 'marco.ranaldi@arsenalia.com',
    level: 'L3',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Silvia',
    lastname: 'Basso',
    email: 'silvia.basso@arsenalia.com',
    level: 'L5',
    role: 'Operations',
    team: 'Operations',
  },
  {
    firstname: 'Dominique Corin',
    lastname: 'Di Pasquale',
    email: 'dominiquecorin.dipasquale@arsenalia.com',
    level: 'L2',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Giulia',
    lastname: 'Utzeri',
    email: 'giulia.utzeri@arsenalia.com',
    level: 'L2',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Guglielmo',
    lastname: 'Alati',
    email: 'guglielmo.alati@arsenalia.com',
    level: 'L6',
    role: 'Dir. Creativa',
    team: 'Dir. Creativa',
  },
  {
    firstname: 'Michela',
    lastname: 'Bortoletto',
    email: 'michela.bortoletto@arsenalia.com',
    level: 'L7',
    role: 'Account',
    team: 'Account',
  },
  {
    firstname: 'Arianna',
    lastname: 'Coccolo',
    email: 'arianna.coccolo@arsenalia.com',
    level: 'L2',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Francesca',
    lastname: 'Fusetti',
    email: 'francesca.fusetti@arsenalia.com',
    level: 'L2',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Cristiana',
    lastname: 'Giora',
    email: 'cristiana.giora@arsenalia.com',
    level: 'L3',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Paola',
    lastname: 'Romano',
    email: 'paola.romano@arsenalia.com',
    level: 'L2',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Valentina',
    lastname: 'Cinetto',
    email: 'valentina.cinetto@arsenalia.com',
    level: 'L5',
    role: 'Operations',
    team: 'Operations',
  },
  {
    firstname: 'Francesco',
    lastname: 'Romano',
    email: 'francesco.romano@arsenalia.com',
    level: 'L2',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Fabio',
    lastname: 'Carraro',
    email: 'fabio.carraro@arsenalia.com',
    level: 'L4',
    role: 'Operations',
    team: 'Operations',
  },
  {
    firstname: 'Gianluca',
    lastname: 'Ruocco Guadagno',
    email: 'gianluca.ruoccoguadagno@arsenalia.com',
    level: 'L6',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Davide',
    lastname: 'Arini',
    email: 'davide.arini@arsenalia.com',
    level: 'L5',
    role: 'Dir. Creativa',
    team: 'Dir. Creativa',
  },
  {
    firstname: 'Eugenia',
    lastname: 'Petrillo',
    email: 'eugenia.petrillo@arsenalia.com',
    level: 'L2',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Elena',
    lastname: 'Mazzucato',
    email: 'elena.mazzucato@arsenalia.com',
    level: 'L5',
    role: 'Account',
    team: 'Account',
  },
  {
    firstname: 'Francesco',
    lastname: 'Vedovato',
    email: 'francesco.vedovato@arsenalia.com',
    level: 'L5',
    role: 'Operations',
    team: 'Operations',
  },
  {
    firstname: 'Marco',
    lastname: 'Lezzerini',
    email: 'marco.lezzerini@arsenalia.com',
    level: 'L4',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Cristina Veronica',
    lastname: 'Pruna',
    email: 'cristinaveronica.pruna@arsenalia.com',
    level: 'L2',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Marco',
    lastname: 'Broglio',
    email: 'marco.broglio@arsenalia.com',
    level: 'L2',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Carlotta',
    lastname: 'Zambet',
    email: 'carlotta.zambet@arsenalia.com',
    level: 'L2',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Stefano',
    lastname: 'Sonda',
    email: 'stefano.sonda@arsenalia.com',
    level: 'L4',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Beatrice',
    lastname: 'Verde',
    email: 'beatrice.verde@arsenalia.com',
    level: 'L2',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Antonio',
    lastname: 'Guiotto',
    email: 'antonio.guiotto@arsenalia.com',
    level: 'L3',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Alessia',
    lastname: 'Dalla Costa',
    email: 'alessia.dallacosta@arsenalia.com',
    level: 'L3',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Enrico',
    lastname: 'Bortoletto',
    email: 'enrico.bortoletto@arsenalia.com',
    level: 'L7',
    role: 'Dir. Creativa',
    team: 'Dir. Creativa',
  },
  {
    firstname: 'Marta',
    lastname: 'Dotto',
    email: 'marta.dotto@arsenalia.com',
    level: 'L2',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Andrea',
    lastname: 'Favaretto',
    email: 'andrea.favaretto@arsenalia.com',
    level: 'L5',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Angela',
    lastname: 'Paciello',
    email: 'angela.paciello@arsenalia.com',
    level: 'L2',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Federica',
    lastname: 'Bignotti',
    email: 'federica.bignotti@arsenalia.com',
    level: 'L2',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Samuele',
    lastname: 'Frassin',
    email: 'samuele.frassin@arsenalia.com',
    level: 'L2',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Andrea',
    lastname: 'Galanti',
    email: 'andrea.galanti@arsenalia.com',
    level: 'L7',
    role: 'Versostudio',
    team: 'Versostudio',
  },
  {
    firstname: 'Elisa',
    lastname: 'Sciascia',
    email: 'elisa.sciascia@arsenalia.com',
    level: 'L2',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Anna',
    lastname: 'Girotto',
    email: 'anna.girotto@arsenalia.com',
    level: 'L2',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Stella',
    lastname: 'Scarpa',
    email: 'stella.scarpa@arsenalia.com',
    level: 'L2',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Giulia',
    lastname: 'Ribaudo',
    email: 'giulia.ribaudo@arsenalia.com',
    level: 'L4',
    role: 'Management',
    team: 'Management',
  },
  {
    firstname: 'Marta',
    lastname: 'Boldrin',
    email: 'marta.boldrin@arsenalia.com',
    level: 'L2',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Riccardo',
    lastname: 'Baggio',
    email: 'riccardo.baggio@arsenalia.com',
    level: 'L2',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Serena',
    lastname: 'Tonon',
    email: 'serena.tonon@arsenalia.com',
    level: 'L2',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Francesca',
    lastname: 'Pavan',
    email: 'francesca.pavan@arsenalia.com',
    level: 'L3',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Elena',
    lastname: 'Longato',
    email: 'elena.longato@arsenalia.com',
    level: 'L4',
    role: 'Operations',
    team: 'Operations',
  },
  {
    firstname: 'Giulia',
    lastname: 'Garelli',
    email: 'giulia.garelli@arsenalia.com',
    level: 'L2',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Beatrice',
    lastname: 'Cocchia',
    email: 'beatrice.cocchia@arsenalia.com',
    level: 'L2',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Linda',
    lastname: 'Mazzer',
    email: 'linda.mazzer@arsenalia.com',
    level: 'L2',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Anna',
    lastname: 'Bertoldero',
    email: 'anna.bertoldero@arsenalia.com',
    level: 'L1',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Alessia',
    lastname: 'Enriquez',
    email: 'alessia.enriquez@arsenalia.com',
    level: 'L1',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Riccardo',
    lastname: 'Menegon',
    email: 'riccardo.menegon@arsenalia.com',
    level: 'L2',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Carlo Giuseppe',
    lastname: 'Calonego',
    email: 'carlogiuseppe.calonego@arsenalia.com',
    level: 'L2',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Marina',
    lastname: 'Deleonardis',
    email: 'marina.deleonardis@arsenalia.com',
    level: 'L6',
    role: 'Sales',
    team: 'Sales',
  },
  {
    firstname: 'Alice',
    lastname: 'Penzo',
    email: 'alice.penzo@arsenalia.com',
    level: 'L2',
    role: 'Reelevate',
    team: 'Reelevate',
  },
  {
    firstname: 'Francesco',
    lastname: 'Berneschi',
    email: 'francesco.berneschi@arsenalia.com',
    level: 'L8',
    role: 'Reelevate',
    team: 'Reelevate',
  },
  {
    firstname: 'Daniele',
    lastname: 'Felicetti',
    email: 'daniele.felicetti@arsenalia.com',
    level: 'L3',
    role: 'Reelevate',
    team: 'Reelevate',
  },
  {
    firstname: 'Luca',
    lastname: 'Marchei',
    email: 'luca.marchei@arsenalia.com',
    level: 'L4',
    role: 'Reelevate',
    team: 'Reelevate',
  },
  {
    firstname: 'Giada',
    lastname: 'Mason',
    email: 'giada.mason@arsenalia.com',
    level: 'L3',
    role: 'Reelevate',
    team: 'Reelevate',
  },
  {
    firstname: 'Jessica',
    lastname: 'Marcon',
    email: 'jessica.marcon@arsenalia.com',
    level: 'L3',
    role: 'Reelevate',
    team: 'Reelevate',
  },
  {
    firstname: 'Adriana',
    lastname: 'Sacchetto',
    email: 'adriana.sacchetto@arsenalia.com',
    level: 'L4',
    role: 'Reelevate',
    team: 'Reelevate',
  },
  {
    firstname: 'Gianluca',
    lastname: 'Piola',
    email: 'gianluca.piola@arsenalia.com',
    level: 'L4',
    role: 'Reelevate',
    team: 'Reelevate',
  },
  {
    firstname: 'Andrea',
    lastname: 'Di Mario',
    email: 'andrea.dimario@arsenalia.com',
    level: 'L8',
    role: 'Reelevate',
    team: 'Reelevate',
  },
  {
    firstname: 'Angjelo',
    lastname: 'Lleshi',
    email: 'angjelo.lleshi@arsenalia.com',
    level: 'L8',
    role: 'Reelevate',
    team: 'Reelevate',
  },
  {
    firstname: 'Alexandru Catalin',
    lastname: 'Duma',
    email: 'alexandrucatalin.duma@arsenalia.com',
    level: 'L3',
    role: 'Reelevate',
    team: 'Reelevate',
  },
  {
    firstname: 'Elisa',
    lastname: 'Fornasa',
    email: 'elisa.fornasa@arsenalia.com',
    level: 'L3',
    role: 'Reelevate',
    team: 'Reelevate',
  },
  {
    firstname: 'Daniele',
    lastname: 'Dominici',
    email: 'daniele.dominici@arsenalia.com',
    level: 'L5',
    role: 'Delivery',
    team: 'Delivery',
  },
  {
    firstname: 'Gioele',
    lastname: 'Mason',
    email: 'gioele.mason@arsenalia.com',
    level: 'L3',
    role: 'Delivery',
    team: 'Delivery',
  },{
    firstname: 'Simonetta',
    lastname: 'Tinotti',
    email: 'simonetta.tinotti@arsenalia.com',
    level: 'L4',
    role: 'delivery',
    team: 'delivery',
  },
  {
    firstname: 'Alessandra',
    lastname: 'Santonastaso',
    email: 'alessandra.santonastaso@arsenalia.com',
    level: 'L4',
    role: 'delivery',
    team: 'delivery',
  },
  {
    firstname: 'Stefania',
    lastname: 'Travaglia',
    email: 'stefania.travaglia@arsenalia.com',
    level: 'L4',
    role: 'delivery',
    team: 'delivery',
  },
  {
    firstname: 'Federica',
    lastname: 'Breda',
    email: 'federica.breda@arsenalia.com',
    level: 'L7',
    role: 'management',
    team: 'management',
  },
  {
    firstname: 'Alessandra',
    lastname: 'Franco Bonafede',
    email: 'alessandra.francobonafede@arsenalia.com',
    level: 'L4',
    role: 'delivery',
    team: 'delivery',
  },
  {
    firstname: 'Elena',
    lastname: 'Tasinato',
    email: 'elena.tasinato@arsenalia.com',
    level: 'L4',
    role: 'delivery',
    team: 'delivery',
  },
  {
    firstname: 'Sabrina',
    lastname: 'Pietrobon',
    email: 'sabrina.pietrobon@arsenalia.com',
    level: 'L4',
    role: 'delivery',
    team: 'delivery',
  },
  {
    firstname: 'Elena',
    lastname: 'Sarzo',
    email: 'elena.sarzo@arsenalia.com',
    level: 'L4',
    role: 'delivery',
    team: 'delivery',
  },
  {
    firstname: 'Claudio',
    lastname: 'Banzato',
    email: 'claudio.banzato@arsenalia.com',
    level: 'L3',
    role: 'delivery',
    team: 'delivery',
  },
  {
    firstname: 'Silvia',
    lastname: 'Santini',
    email: 'silvia.santini@arsenalia.com',
    level: 'L4',
    role: 'TL',
    team: 'TL',
  },
  {
    firstname: 'Roberto',
    lastname: 'Cosma',
    email: 'roberto.cosma@arsenalia.com',
    level: 'L6',
    role: 'delivery',
    team: 'delivery',
  },
  {
    firstname: 'Giorgina',
    lastname: 'Sturaro',
    email: 'giorgina.sturaro@arsenalia.com',
    level: 'L4',
    role: 'delivery',
    team: 'delivery',
  },
  {
    firstname: 'Francesco',
    lastname: 'Fontanieri',
    email: 'francesco.fontanieri@arsenalia.com',
    level: 'L4',
    role: 'delivery',
    team: 'delivery',
  },
  {
    firstname: 'Matteo',
    lastname: 'Zaggia',
    email: 'matteo.zaggia@arsenalia.com',
    level: 'L4',
    role: 'TL',
    team: 'TL',
  },
  {
    firstname: 'Stefania',
    lastname: 'Burattin',
    email: 'stefania.burattin@arsenalia.com',
    level: 'L4',
    role: 'delivery',
    team: 'delivery',
  },
  {
    firstname: 'Grazia',
    lastname: 'Generali',
    email: 'grazia.generali@arsenalia.com',
    level: 'L3',
    role: 'delivery',
    team: 'delivery',
  },
  {
    firstname: 'Giovanni Maria',
    lastname: 'Bozzolan',
    email: 'giovannimaria.bozzolan@arsenalia.com',
    level: 'L3',
    role: 'delivery',
    team: 'delivery',
  },
  {
    firstname: 'Filippo',
    lastname: 'Pavin',
    email: 'filippo.pavin@arsenalia.com',
    level: 'L3',
    role: 'delivery',
    team: 'delivery',
  },
  {
    firstname: 'Enrico',
    lastname: 'Finucci',
    email: 'enrico.finucci@arsenalia.com',
    level: 'L2',
    role: 'delivery',
    team: 'delivery',
  },
  {
    firstname: 'Giulio',
    lastname: 'Zulian',
    email: 'giulio.zulian@arsenalia.com',
    level: 'L5',
    role: 'TL',
    team: 'TL',
  },
  {
    firstname: 'Marco',
    lastname: 'Lazzari',
    email: 'marco.lazzari@arsenalia.com',
    level: 'L4',
    role: 'delivery',
    team: 'delivery',
  },
  {
    firstname: 'Alice',
    lastname: 'Santi',
    email: 'alice.santi@arsenalia.com',
    level: 'L4',
    role: 'account',
    team: 'account',
  },
  {
    firstname: 'Carlo',
    lastname: 'Sandonà',
    email: 'carlo.sandona@arsenalia.com',
    level: 'L4',
    role: 'TL',
    team: 'TL',
  },
  {
    firstname: 'Alessandro',
    lastname: 'Filira',
    email: 'alessandro.filira@arsenalia.com',
    level: 'L5',
    role: 'TL',
    team: 'TL',
  },
  {
    firstname: 'Laura',
    lastname: 'Lazzarin',
    email: 'laura.lazzarin@arsenalia.com',
    level: 'L4',
    role: 'delivery',
    team: 'delivery',
  },
  {
    firstname: 'Sandra',
    lastname: 'Mitrovic',
    email: 'sandra.mitrovic@arsenalia.com',
    level: 'L5',
    role: 'account',
    team: 'account',
  },
  {
    firstname: 'Luca',
    lastname: 'Zocca',
    email: 'luca.zocca@arsenalia.com',
    level: 'L3',
    role: 'delivery',
    team: 'delivery',
  },
  {
    firstname: 'Samuele',
    lastname: 'Favaro',
    email: 'samuele.favaro@arsenalia.com',
    level: 'L3',
    role: 'delivery',
    team: 'delivery',
  },
  {
    firstname: 'Ylenia',
    lastname: 'Chinello',
    email: 'ylenia.chinello@arsenalia.com',
    level: 'L2',
    role: 'delivery',
    team: 'delivery',
  },
  {
    firstname: 'Cristian',
    lastname: 'Buja',
    email: 'cristian.buja@arsenalia.com',
    level: 'L3',
    role: 'delivery',
    team: 'delivery',
  },
  {
    firstname: 'Ilaria',
    lastname: 'Tibaldi',
    email: 'ilaria.tibaldi@arsenalia.com',
    level: 'L3',
    role: 'delivery',
    team: 'delivery',
  },
  {
    firstname: 'Federica',
    lastname: 'Tommasi',
    email: 'federica.tommasi@arsenalia.com',
    level: 'L3',
    role: 'delivery',
    team: 'delivery',
  },
  {
    firstname: 'Lisa',
    lastname: 'Zanardo',
    email: 'lisa.zanardo@arsenalia.com',
    level: 'L2',
    role: 'delivery',
    team: 'delivery',
  },
  {
    firstname: 'Gabriele',
    lastname: 'Parpaiola',
    email: 'gabriele.parpaiola@arsenalia.com',
    level: 'L4',
    role: 'delivery',
    team: 'delivery',
  },
  {
    firstname: 'Mattia',
    lastname: 'Bertoldo',
    email: 'mattia.bertoldo@arsenalia.com',
    level: 'L2',
    role: 'delivery',
    team: 'delivery',
  },
  {
    firstname: 'Elena',
    lastname: 'Ganz',
    email: 'elena.ganz@arsenalia.com',
    level: 'L3',
    role: 'delivery',
    team: 'delivery',
  },
  {
    firstname: 'Caterina',
    lastname: 'Maniero',
    email: 'caterina.maniero@arsenalia.com',
    level: 'L2',
    role: 'delivery',
    team: 'delivery',
  },
  {
    firstname: 'Cristina',
    lastname: 'Vedovetto',
    email: 'cristina.vedovetto@arsenalia.com',
    level: 'L3',
    role: 'delivery',
    team: 'delivery',
  },
  {
    firstname: 'Camilla',
    lastname: 'Galetto',
    email: 'camilla.galetto@arsenalia.com',
    level: 'L3',
    role: 'delivery',
    team: 'delivery',
  },
  {
    firstname: 'Chiara',
    lastname: 'Friso',
    email: 'chiara.friso@arsenalia.com',
    level: 'L2',
    role: 'delivery',
    team: 'delivery',
  },
  {
    firstname: 'Nicola',
    lastname: 'Fantin',
    email: 'nicola.fantin@arsenalia.com',
    level: 'L4',
    role: 'delivery',
    team: 'delivery',
  },
  {
    firstname: 'Giovanna',
    lastname: 'Venturato',
    email: 'giovanna.venturato@arsenalia.com',
    level: 'L4',
    role: 'delivery',
    team: 'delivery',
  },
  {
    firstname: 'Giada',
    lastname: 'Ripamonti',
    email: 'giada.ripamonti@arsenalia.com',
    level: 'L2',
    role: 'delivery',
    team: 'delivery',
  },
  {
    firstname: 'Greta',
    lastname: 'Alberghini',
    email: 'greta.alberghini@arsenalia.com',
    level: 'L2',
    role: 'delivery',
    team: 'delivery',
  },
  {
    firstname: 'Federico',
    lastname: 'Bernardin',
    email: 'federico.bernardin@arsenalia.com',
    level: 'L7',
    role: 'sales',
    team: 'sales',
  },
  {
    firstname: 'Valentina',
    lastname: 'Persia',
    email: 'valentina.persia@arsenalia.com',
    level: 'L2',
    role: 'delivery',
    team: 'delivery',
  },
  {
    firstname: 'Marcio Fernando',
    lastname: 'Beltramin',
    email: 'marciofernando.beltramin@arsenalia.com',
    level: 'L4',
    role: 'delivery',
    team: 'delivery',
  },
  {
    firstname: 'Luca',
    lastname: 'Dalla Costa',
    email: 'luca.dallacosta@arsenalia.com',
    level: 'L3',
    role: 'delivery',
    team: 'delivery',
  },
  {
    firstname: 'Franco',
    lastname: 'Scarpa',
    email: 'franco.scarpa@arsenalia.com',
    level: 'L2',
    role: 'management',
    team: 'management',
  },
  {
    firstname: 'Alessia',
    lastname: 'Marchesan',
    email: 'alessia.marchesan@arsenalia.com',
    level: 'L3',
    role: 'delivery',
    team: 'delivery',
  },
  {
    firstname: 'Giorgio',
    lastname: 'Russo',
    email: 'giorgio.russo@arsenalia.com',
    level: 'L2',
    role: 'delivery',
    team: 'delivery',
  },
  {
    firstname: 'Enrico',
    lastname: 'Antonello',
    email: 'enrico.antonello@arsenalia.com',
    level: 'L5',
    role: 'delivery',
    team: 'delivery',
  },
  {
    firstname: 'Eduard',
    lastname: 'Lisnic',
    email: 'eduard.lisnic@arsenalia.com',
    level: 'L2',
    role: 'delivery',
    team: 'delivery',
  },
  {
    firstname: 'Leonardo',
    lastname: 'Liziero',
    email: 'leonardo.liziero@arsenalia.com',
    level: 'L3',
    role: 'delivery',
    team: 'delivery',
  },
  {
    firstname: 'Giovanni',
    lastname: 'Persico',
    email: 'giovanni.persico@arsenalia.com',
    level: 'L3',
    role: 'delivery',
    team: 'delivery',
  },
];

    console.log(`📊 Preparing to insert ${peopleData.length} construction periods...`);

    // Puliamo la tabella prima di inserire
    await db.delete(people);
    console.log('🧹 Cleared existing data from vetusta table');

    // Inseriamo i nuovi dati
    await db.insert(people).values(peopleData);

    console.log('✅ Successfully seeded VETUSTÀ table!');
    console.log(`📈 Total construction periods inserted: ${peopleData.length}`);
    
    // Verifichiamo l'inserimento
    const insertedData = await db.select().from(people);
    console.log('\n📋 Inserted data:');
    insertedData.forEach((item) => {
      console.log(`   ${item.firstname} ${item.lastname} | ${item.email} | ${item.level} | ${item.role} | ${item.team}`);
    });

  } catch (error) {
    console.error('❌ Error seeding VETUSTÀ table:', error);
    if (error instanceof Error) {
      console.error('Error details:', {
        message: error.message,
        stack: error.stack,
      });
    }
    process.exit(1);
  }
}

seedPeople();