// script/seed-vetusta.ts
import { seedDb as db } from '../seed-config';
import { projects } from '../schema';

const projectsData = [
  {
    type: 'Progetto',
    client: 'Emilio pucci srl',
    order: 'Emilio Pucci copy DTC25',
    pm: 'Gianluca Piola',
  },
  {
    type: 'Progetto',
    client: 'Volkswagen',
    order: 'CRO VW (tesoretto service) su VW Service Serviceweb 2024',
    pm: 'Silvia Santini',
  },
  {
    type: 'Progetto',
    client: 'Volkswagen',
    order: 'CRO VW (su VW Service Serviceweb1124-1025(40004907))',
    pm: 'Silvia Santini',
  },
  {
    type: 'Progetto',
    client: 'ULSS 1',
    order: 'Ulss1 campagna prevenzione Melanoma',
    pm: 'Silvia Santini',
  },
  {
    type: 'Progetto',
    client: 'Plastotecnica',
    order: 'Plastotecnica migrazione contenuti',
    pm: 'Giovanna Venturato',
  },
  {
    type: 'Progetto',
    client: 'Plastotecnica',
    order: 'Plastotecnica nuovo sito web',
    pm: 'Giovanna Venturato',
  },
  {
    type: 'Progetto',
    client: 'Bata',
    order: 'Bata t&m anticipato 2025',
    pm: 'Carlotta Zambet',
  },
  {
    type: 'Progetto',
    client: 'Lorenzi Milano',
    order: 'Lorenzi Milano social DTC25',
    pm: 'Carlotta Zambet',
  },
  {
    type: 'Progetto',
    client: 'Lorenzi Milano',
    order: 'Lorenzi Milano photo shoot still',
    pm: 'Carlotta Zambet',
  },
  {
    type: 'Progetto',
    client: 'Theras Lifetech S.r.l',
    order: 'Theras AMS DTC 2025',
    pm: 'Fabio Carraro',
  },
  {
    type: 'Progetto',
    client: 'Ligabue',
    order: 'Ligabue linkedin e wpc check DTC 2024',
    pm: 'Fabio Carraro',
  },
  {
    type: 'Progetto',
    client: 'Ligabue',
    order: 'Ligabue communication DTC25',
    pm: 'Fabio Carraro',
  },
  {
    type: 'Progetto',
    client: 'Ligabue',
    order: 'Ligabue Magazine',
    pm: 'Federica Tommasi',
  },
  {
    type: 'Progetto',
    client: 'Cigierre',
    order: 'Cigierre Smashie attività t&m',
    pm: 'Gianluca Piola',
  },
  {
    type: 'Progetto',
    client: 'Cigierrre',
    order: 'Cigierre Smashie attività t&m',
    pm: 'Gianluca Piola',
  },
  {
    type: 'OH',
    client: 'Arsenalia Digital',
    order: 'OH - management arsenalia digital',
    pm: 'Elena Longato',
  },
  {
    type: 'Progetto',
    client: 'Save',
    order: 'SAVE website e comunicazione',
    pm: 'Roberto Cosma',
  },
  {
    type: 'Progetto',
    client: 'Coin',
    order: 'Coin comunicazione DTC 2025',
    pm: 'Elisa Sciascia',
  },
  {
    type: 'Progetto',
    client: 'IEGEXPO',
    order: 'IEG (Amplize) Rubicon',
    pm: 'Eric Bosco',
  },
  {
    type: 'Progetto',
    client: 'Pavoni Italia',
    order: 'Pavoni DTC 2025',
    pm: 'Carlotta Zambet',
  },
  {
    type: 'Progetto',
    client: 'Lorenzi Milano',
    order: 'Lorenzi Milano T&m shopify',
    pm: 'Carlotta Zambet',
  },
  {
    type: 'Progetto',
    client: 'Pasta Zara',
    order: 'R- Pasta Zara lotto 4 SMM DTC 2025',
    pm: 'Elisa Sciascia',
  },
  {
    type: 'Progetto',
    client: 'Pasta Zara',
    order: 'T&M 2025',
    pm: 'Elisa Sciascia',
  },
  {
    type: 'Progetto',
    client: 'Connubia',
    order: 'Calligaris Social e Contenuti DTC25',
    pm: 'Francesca Pavan',
  },
  {
    type: 'Progetto',
    client: 'Calligaris',
    order: 'Calligaris Social e Contenuti DTC25',
    pm: 'Francesca Pavan',
  },
  {
    type: 'Progetto',
    client: 'Gefran Spa',
    order: 'Gefran pack t&m anticipato',
    pm: 'Francesca Pavan',
  },
  {
    type: 'Progetto',
    client: 'Automobili Lamborghini',
    order: 'VS- Lamborghini corner sostenibilità 25',
    pm: 'Filippo Stocco',
  },
  {
    type: 'Progetto',
    client: 'mdf Italia',
    order: 'MDF Manutenzione DTC 2025',
    pm: 'Greta Alberghini',
  },
  {
    type: 'Progetto',
    client: 'Mitsubishi',
    order: 'Mitsubishi T&M H2-2025',
    pm: 'Giovanna Venturato',
  },
  {
    type: 'Progetto',
    client: 'Sirmax',
    order: 'Sirmax manutenzione 2025',
    pm: 'Giovanna Venturato',
  },
  {
    type: 'Progetto',
    client: 'Audi',
    order: 'Audi aggiorn. Servicenet 2025',
    pm: 'Giovanna Venturato',
  },
  {
    type: 'Progetto',
    client: 'Calligaris',
    order: 'Calligaris (Alpenite) new B2C com layer',
    pm: 'Xhorxhina Molla',
  },
  {
    type: 'Progetto',
    client: 'Coin SpA',
    order: 'Coin Progetto Natale',
    pm: 'Elisa Sciascia',
  },
  {
    type: 'Progetto',
    client: 'Autosile',
    order: 'Autosile digital marketing DTC 2025',
    pm: 'Fabio Carraro',
  },
  {
    type: 'Progetto',
    client: 'GPBL',
    order: 'GPBL',
    pm: 'Fabio Carraro',
  },
  {
    type: 'Progetto',
    client: 'Automobili Lamborghini',
    order: 'Lamborghini Contratto Quadro 2025',
    pm: 'Filippo Stocco',
  },
  {
    type: 'Progetto',
    client: 'OTB',
    order: 'OTV 2025',
    pm: 'Filippo Stocco',
  },
  {
    type: 'Progetto',
    client: 'AFOR',
    order: 'Afor Comunicazione',
    pm: 'Filippo Stocco',
  },
  {
    type: 'Progetto',
    client: 'Decathlon',
    order: 'Decathlon (Amplize) DTC Marketing Operation25',
    pm: 'Marta Pegoraro',
  },
  {
    type: 'Progetto',
    client: 'Weekend MaxMara',
    order: 'Weekend Giuliva Essentials',
    pm: 'Filippo Stocco',
  },
  {
    type: 'Progetto',
    client: 'MAN',
    order: 'MAN Processo di Gest Sconti',
    pm: 'Silvia Santini',
  },
  {
    type: 'Progetto',
    client: 'MAN',
    order: 'MAN Manutenzione',
    pm: 'Silvia Santini',
  },
  {
    type: 'Progetto',
    client: 'MAN',
    order: 'MAN MAnutenzione',
    pm: 'Silvia Santini',
  },
  {
    type: 'Progetto',
    client: 'MAN',
    order: 'MAN supporto comunicazione 2025',
    pm: 'Silvia Santini',
  },
  {
    type: 'Progetto',
    client: 'VGI',
    order: 'Manutenzione 2025',
    pm: 'Silvia Santini',
  },
  {
    type: 'Progetto',
    client: 'Haier Europe',
    order: 'Haier Europe - website manteinance',
    pm: 'Filippo Stocco',
  },
  {
    type: 'Progetto',
    client: 'AGF',
    order: 'AGF Supporto T&M 2025',
    pm: 'Camilla Galetto',
  },
  {
    type: 'Progetto',
    client: 'Peserico',
    order: 'T&M',
    pm: 'Gianluca Piola',
  },
  {
    type: 'Progetto',
    client: 'UILDM Nazionale',
    order: 'UILDM piano di com.2025MatchPointV2',
    pm: 'Giovanna Venturato',
  },
  {
    type: 'Progetto',
    client: 'Fidia',
    order: 'Fidia start progetti 2025',
    pm: 'Carlotta Zambet',
  },
  {
    type: 'Progetto',
    client: 'Brunello Cucinelli',
    order: 'Brunello Cucinelli des&dev T&M2025',
    pm: 'Francesco Vedovato',
  },
  {
    type: 'Progetto',
    client: 'Brunello Cucinelli',
    order: 'Brunello Cucinelli content SFCC DTC 2025',
    pm: 'Francesco Vedovato',
  },
  {
    type: 'Progetto',
    client: 'FEDRIGONI S.P.A.',
    order: 'Magnani (Fedrigoni) T&M anticipato 25',
    pm: 'Gianluca Piola',
  },
  {
    type: 'Progetto',
    client: 'Art Cosmetics Srl',
    order: 'VS- Art Cosmetics DTC Cosmoprof 2025',
    pm: 'Francesca Pavan',
  },
  {
    type: 'Pitch',
    client: 'Siretessile',
    order: 'Siretessile pitch',
    pm: 'Filippo Stocco',
  },
  {
    type: 'Progetto',
    client: 'ccelera',
    order: 'De Rigo ccelera B2b',
    pm: 'Filippo Stocco',
  },
  {
    type: 'Progetto',
    client: 'Benestore',
    order: 'Benestore',
    pm: 'Alberto Baesso',
  },
  {
    type: 'Progetto',
    client: 'Benestore',
    order: 'Benestore (Alpenite) Redesign eComm 2025',
    pm: 'Alberto Baesso',
  },
  {
    type: 'Progetto',
    client: 'Coin',
    order: 'Coin store management DTC 2025',
    pm: 'Elisa Sciascia',
  },
  {
    type: 'Progetto',
    client: 'Fantic',
    order: 'Fantic e-commerce',
    pm: 'Valentina Cinetto',
  },
  {
    type: 'Progetto',
    client: 'Polyglass',
    order: 'Polyglass T&M Support Q425',
    pm: 'Elisa Sciascia',
  },
  {
    type: 'Progetto',
    client: 'Vestopazzo',
    order: 'Vestopazzo branding',
    pm: 'Filippo Stocco',
  },
  {
    type: 'Progetto',
    client: "Tod's",
    order: "Tod's Group Adobe Campaign Digital Total Care 2024",
    pm: 'Ilaria Magrin',
  },
  {
    type: 'Progetto',
    client: 'Zegna',
    order: 'Zegna (ValuePartners) content 2024',
    pm: 'Serena Tonon',
  },
  {
    type: 'Progetto',
    client: 'Bulgari',
    order: 'Bulgari digital mkgt restyling',
    pm: 'Silvia Basso',
  },
  {
    type: 'Progetto',
    client: 'Bulgari',
    order: 'Bulgari omnichannel DTC 2025',
    pm: 'Silvia Basso',
  },
  {
    type: 'Progetto',
    client: 'GG',
    order: 'Content Factory Digital Total Care 2024',
    pm: 'Elena Longato',
  },
  {
    type: 'Progetto',
    client: 'GG',
    order: 'GG redesign sito Haus',
    pm: 'Elena Longato',
  },
  {
    type: 'Progetto',
    client: 'GGDB',
    order: 'GG wesmash mail',
    pm: 'Elena Longato',
  },
  {
    type: 'Progetto',
    client: 'GGDB',
    order: 'GG wesmash onepage',
    pm: 'Elena Longato',
  },
  {
    type: 'Progetto',
    client: 'UnipolSai',
    order: 'UnipolSai consulenza T&M 2025',
    pm: 'Camilla Galetto',
  },
  {
    type: 'OH',
    client: 'Arsenalia Digital',
    order: 'Marketing Arsenalia',
    pm: 'Sebastiano Loni',
  },
  {
    type: 'OH',
    client: 'Arsenalia Digital',
    order: 'Marketing Arsenalia - (attività specifica Biennale)',
    pm: 'Sebastiano Loni',
  },
  {
    type: 'Progetto',
    client: 'Volkswagen',
    order: 'VW Manutenzione siti nov25-ott25',
    pm: 'Ilaria Tibaldi',
  },
  {
    type: 'Progetto',
    client: 'Volkswagen',
    order: 'VW Manutenzione siti nov24-ott25',
    pm: 'Ilaria Tibaldi',
  },
  {
    type: 'Progetto',
    client: 'Volkswagen',
    order: 'VW Report nov24-ott25',
    pm: 'Ilaria Tibaldi',
  },
  {
    type: 'Progetto',
    client: 'Volkswagen',
    order: 'VW Listini nov24-ott25',
    pm: 'Ilaria Tibaldi',
  },
  {
    type: 'Progetto',
    client: 'Volkswagen',
    order: 'VW Dealerweb nov24-ott25',
    pm: 'Ilaria Tibaldi',
  },
  {
    type: 'Progetto',
    client: 'Volkswagen',
    order: 'VW Dealerweb nov24-ott25 (form FA offers)',
    pm: 'Ilaria Tibaldi',
  },
  {
    type: 'Progetto',
    client: 'Volkswagen',
    order: 'VW Usato Certificato nov25-dic25',
    pm: 'Laura Lazzarin',
  },
  {
    type: 'Progetto',
    client: 'Volkswagen',
    order: 'VW Future Sales Portal 2025',
    pm: 'Ilaria Tibaldi',
  },
  {
    type: 'Progetto',
    client: 'AFR',
    order: 'AFR manutenzione website DTC 2025',
    pm: 'Ilaria Tibaldi',
  },
  {
    type: 'Progetto',
    client: 'AFR',
    order: 'Gestione social AFR e Bassini',
    pm: 'Ilaria Tibaldi',
  },
  {
    type: 'Progetto',
    client: 'Volkswagen',
    order: 'VW Form nov24-ott25',
    pm: 'Francesca Carrer',
  },
  {
    type: 'Progetto',
    client: 'Volkswagen',
    order: 'VW CRM nov24-ott25',
    pm: 'Francesca Carrer',
  },
  {
    type: 'Progetto',
    client: 'Volkswagen',
    order: 'VW ADV',
    pm: 'Francesca Carrer',
  },
  {
    type: 'Progetto',
    client: 'Volkswagen',
    order: 'VW Car Configurator nov25-dic25',
    pm: 'Laura Lazzarin',
  },
  {
    type: 'Progetto',
    client: 'Volkswagen',
    order: 'VW Car Configurator nov25-dic26',
    pm: 'Laura Lazzarin',
  },
  {
    type: 'Progetto',
    client: 'Volkswagen',
    order: 'VW FS Salesbook',
    pm: 'Laura Lazzarin',
  },
  {
    type: 'Progetto',
    client: 'Volkswagen Service',
    order: 'VW Service Serviceweb nov24-ott25',
    pm: 'Greta Alberghini',
  },
  {
    type: 'Progetto',
    client: 'Volkswagen Service',
    order: 'VW Service ADV nov24-ott25',
    pm: 'Greta Alberghini',
  },
  {
    type: 'Progetto',
    client: 'Volkswagen Service',
    order: 'VW Service Applicativi nov24-ott25',
    pm: 'Greta Alberghini',
  },
  {
    type: 'Progetto',
    client: 'Volkswagen Service',
    order: 'VW Service Report nov24-ott25',
    pm: 'Greta Alberghini',
  },
  {
    type: 'Progetto',
    client: 'Volkswagen Flotte',
    order: 'VW Flotte nov-dec25',
    pm: 'Luca Dalla Costa',
  },
  {
    type: 'Progetto',
    client: 'Volkswagen VIC',
    order: 'VIC (VW) manutenzione gen-ott 2025',
    pm: 'Cristina Vedovetto',
  },
  {
    type: 'Progetto',
    client: 'Volkswagen VIC',
    order: 'VIC (VW) manutenzione gen-ott 2026',
    pm: 'Cristina Vedovetto',
  },
  {
    type: 'Progetto',
    client: 'Audi',
    order: 'Audi dem 2025',
    pm: 'Elena Ganz',
  },
  {
    type: 'Progetto',
    client: 'Audi',
    order: 'Audi campagne DCO 2025',
    pm: 'Elena Ganz',
  },
  {
    type: 'Progetto',
    client: 'Audi',
    order: 'Audi CC 2025',
    pm: 'Elena Ganz',
  },
  {
    type: 'Progetto',
    client: 'Audi',
    order: 'Audi sito minisiti VTP 2025',
    pm: 'Elena Ganz',
  },
  {
    type: 'Progetto',
    client: 'Audi',
    order: 'Audi form prodotto service e report 2025',
    pm: 'Elena Ganz',
  },
  {
    type: 'Progetto',
    client: 'Audi',
    order: 'Audi SW e DW ge-ott 2025',
    pm: 'Camilla Galetto',
  },
  {
    type: 'Progetto',
    client: 'Audi',
    order: 'Audi report-form-caroselli 2025',
    pm: 'Camilla Galetto',
  },
  {
    type: 'Progetto',
    client: 'Audi',
    order: 'Audi report-form-caroselli 2025',
    pm: 'Elena Ganz',
  },
  {
    type: 'Progetto',
    client: 'Audi',
    order: 'Audi service gen-ott 2025',
    pm: 'Camilla Galetto',
  },
  {
    type: 'Progetto',
    client: 'Audi',
    order: 'Audi serviceweb',
    pm: 'Camilla Galetto',
  },
  {
    type: 'Progetto',
    client: 'SEAT',
    order: 'SEAT CUPRA (VW) CC 2025',
    pm: 'Luca Dalla Costa',
  },
  {
    type: 'Progetto',
    client: 'SEAT',
    order: 'SEAT-CUPRA (VW) DW + SW 2025',
    pm: 'Luca Dalla Costa',
  },
  {
    type: 'Progetto',
    client: 'Valentino',
    order: 'Valentino NL DTC 2025',
    pm: 'Valentina Cinetto',
  },
  {
    type: 'Progetto',
    client: 'Valentino',
    order: 'Valentino Restyle NL',
    pm: 'Valentina Cinetto',
  },
  {
    type: 'Progetto',
    client: 'Pizza New',
    order: 'Pizza New social DTC 2025',
    pm: 'Giovanna Venturato',
  },
  {
    type: 'Progetto',
    client: 'NIMS',
    order: 'NIMS gestione content',
    pm: 'Camilla Galetto',
  },
  {
    type: 'Progetto',
    client: 'NIMS',
    order: 'Nims gestione content',
    pm: 'Camilla Galetto',
  },
  {
    type: 'Progetto',
    client: 'UILDM',
    order: 'UILDM manutenzione e supporto',
    pm: 'Giovanna Venturato',
  },
  {
    type: 'Progetto',
    client: 'Somfy',
    order: 'Somfy manutenzione DTC 2025',
    pm: 'Federica Tommasi',
  },
  {
    type: 'Progetto',
    client: 'Nims',
    order: 'Nims DTC 2025',
    pm: 'Camilla Galetto',
  },
  {
    type: 'Progetto',
    client: 'Profoffice',
    order: 'ProfOffice SEO DTC 2025',
    pm: 'Greta Alberghini',
  },
  {
    type: 'Progetto',
    client: 'Scavolini',
    order: 'Scavolini',
    pm: 'Luca Dalla Costa',
  },
  {
    type: 'Progetto',
    client: 'Volkswagen',
    order: 'VIT (VW) manut applicazioni AWS 2025',
    pm: 'Roberto Cosma',
  },
  {
    type: 'Progetto',
    client: 'Profoffice',
    order: 'ProfOffice supporto attività DTC25',
    pm: 'Greta Alberghini',
  },
  {
    type: 'Progetto',
    client: 'Prof',
    order: 'ProfOffice supporto attività DTC25',
    pm: 'Greta Alberghini',
  },
  {
    type: 'Progetto',
    client: 'FIAMM',
    order: 'FIAMM Comms 2025',
    pm: 'Giovanna Venturato',
  },
  {
    type: 'Progetto',
    client: 'FIAMM',
    order: 'FIAMM Reserve 2025',
    pm: 'Giovanna Venturato',
  },
  {
    type: 'Progetto',
    client: 'Mazzer',
    order: 'Mazzer DTC ADV 25',
    pm: 'Francesca Pavan',
  },
  {
    type: 'Progetto',
    client: 'Lorenzi Milano',
    order: 'Lorenzi rinnovo ADV DTC25',
    pm: 'Carlotta Zambet',
  },
  {
    type: 'Progetto',
    client: 'Pasta Zara',
    order: 'R- Pasta Zara lotto 2 ADV DTC 2025',
    pm: 'Elisa Sciascia',
  },
  {
    type: 'Progetto',
    client: 'Amplize',
    order: 'IEG (Amplize) Rubicon',
    pm: 'Eric Bosco',
  },
  {
    type: 'Progetto',
    client: 'Amplize',
    order: 'IEG (Amplize) Refining Rimini Wellness25',
    pm: 'Eric Bosco',
  },
  {
    type: 'Progetto',
    client: 'Imperial',
    order: 'Imperial ADV DTC 2025',
    pm: 'Gianluca Piola',
  },
  {
    type: 'Progetto',
    client: 'Peg Perego Spa',
    order: 'Peg Perego ADV DTC 2025',
    pm: 'Gianluca Piola',
  },
  {
    type: 'Progetto',
    client: 'Aeronautica Militare',
    order: 'Aeronautica Militare SEO DTC 2025',
    pm: 'Gianluca Piola',
  },
  {
    type: 'Progetto',
    client: 'Aeronautica Militare',
    order: 'Aeronautica Militare ADV DTC 2025',
    pm: 'Gianluca Piola',
  },
  {
    type: 'Progetto',
    client: 'Kask',
    order: 'KASK servizio ADV DTC 2025',
    pm: 'Gianluca Piola',
  },
  {
    type: 'Progetto',
    client: 'Brave Kid',
    order: 'Brave Kid SEO DTC 2025',
    pm: 'Silvia Santini',
  },
  {
    type: 'Progetto',
    client: 'Brave Kid',
    order: 'Brave Kid ADV DTC 2025',
    pm: 'Silvia Santini',
  },
  {
    type: 'Progetto',
    client: 'Marco Bicego',
    order: 'Marco Bicego SEO DTC 2025',
    pm: 'Silvia Santini',
  },
  {
    type: 'Progetto',
    client: 'Marco Bicego',
    order: 'Marco Bicego ADV DTC 2025',
    pm: 'Silvia Santini',
  },
  {
    type: 'Progetto',
    client: "Caddy's",
    order: "Caddy's (DMO) ADV DTC25",
    pm: 'Angjelo Lleshi',
  },
  {
    type: 'Progetto',
    client: 'Isola dei Tesori',
    order: 'R- Isola dei Tesori (DMO PET) ADV DTC 25',
    pm: 'Angjelo Lleshi',
  },
  {
    type: 'Progetto',
    client: 'Isola dei Tesori',
    order: 'R- Isola dei Tesori (DMO) SEO DTC 25',
    pm: 'Angjelo Lleshi',
  },
  {
    type: 'Progetto',
    client: 'Beauty Star',
    order: 'R- Beauty Star (DMO) ADV 2025',
    pm: 'Andrea Di Mario',
  },
  {
    type: 'Progetto',
    client: 'Gas Jeans',
    order: 'GAS Jeans ADV DTC25',
    pm: 'Angjelo Lleshi',
  },
  {
    type: 'Progetto',
    client: 'Calligaris',
    order: 'Calligaris Gestione ADV&SEO DTC25',
    pm: 'Francesca Pavan',
  },
  {
    type: 'Progetto',
    client: 'Montelvini',
    order: 'Montelvini ADV',
    pm: 'Gianluca Piola',
  },
  {
    type: 'Progetto',
    client: 'Fondazione Ligabue',
    order: 'R- Ligabue ADV 2025',
    pm: 'Fabio Carraro',
  },
  {
    type: 'Progetto',
    client: 'San Marco',
    order: 'R- San Marco ADV 2025',
    pm: 'Andrea Di Mario',
  },
  {
    type: 'Progetto',
    client: 'YouPower CH',
    order: 'YouPower CH ADV DTC 2025',
    pm: 'Angjelo Lleshi',
  },
  {
    type: 'Progetto',
    client: 'SAVE',
    order: 'SAVE',
    pm: 'Roberto Cosma',
  },
  {
    type: 'Progetto',
    client: 'GSE',
    order: 'R- GSE Italia ADV 2025',
    pm: 'Andrea Di Mario',
  },
  {
    type: 'Progetto',
    client: 'IC - Altitudo',
    order: 'Lenstore ADV AI Integration',
    pm: 'Angjelo Lleshi',
  },
  {
    type: 'Progetto',
    client: 'Beauty Star',
    order: 'R- Beauty Star (DMO) SEO 2025',
    pm: 'Andrea Di Mario',
  },
  {
    type: 'Progetto',
    client: "Caddy's",
    order: "R- Caddy's (DMO) SEO 2025",
    pm: 'Angjelo Lleshi',
  },
  {
    type: 'Progetto',
    client: 'Giesse Scampoli',
    order: 'Giesse ADV DTC 2025',
    pm: 'Silvia Santini',
  },
  {
    type: 'Progetto',
    client: 'Gefran Spa',
    order: 'Gefran consulenza SEO DTC25',
    pm: 'Francesca Pavan',
  },
  {
    type: 'Progetto',
    client: 'Calligaris',
    order: 'Calligaris SEO e Dig.An. nuovo sito B2C',
    pm: 'Francesca Pavan',
  },
  {
    type: 'Progetto',
    client: 'Imperial',
    order: 'Channable',
    pm: 'Gianluca Piola',
  },
  {
    type: 'Progetto',
    client: 'Zenith',
    order: 'Zenith (Alpenite) Watches DTC 2025',
    pm: 'Xhorxhina Molla',
  },
  {
    type: 'Progetto',
    client: 'Autosystem',
    order: 'Autosystem Supporto Comunicazione Social',
    pm: 'Fabio Carraro',
  },
  {
    type: 'Progetto',
    client: 'Sviluppo Immobiliare Corio',
    order: 'SIC materiale lead generation',
    pm: 'Luca Dalla Costa',
  },
  {
    type: 'Progetto',
    client: 'Sviluppo Immobiliare Corio',
    order: 'SIC ADV DTC 2025',
    pm: 'Andrea Di Mario',
  },
  {
    type: 'Progetto',
    client: 'VGI',
    order: 'VGI Migrazione app su container AWS',
    pm: 'Roberto Cosma',
  },
  {
    type: 'Progetto',
    client: 'vVardis',
    order: 'Vvardis (Arsenalia CH) SF mktg p1 T&M 2025',
    pm: 'Eric Bosco',
  },
  {
    type: 'Progetto',
    client: 'Sephora',
    order: 'Sephora Social&Content 2025',
    pm: 'Carlotta Zambet',
  },
  {
    type: 'Progetto',
    client: 'Yamamay',
    order: 'Yamamay (Alpenite) B2C Shopify design',
    pm: 'Alberto Amadio',
  },
  {
    type: 'Progetto',
    client: 'VGI',
    order: 'Adeguamento applicazioni legacy',
    pm: 'Roberto Cosma',
  },
  {
    type: 'Progetto',
    client: 'VGI',
    order: 'IXSS',
    pm: 'Roberto Cosma',
  },
  {
    type: 'Progetto',
    client: 'SAIT',
    order: 'Sait ADV 2025',
    pm: 'Gianluca Piola',
  },
  {
    type: 'Progetto',
    client: 'Atroos',
    order: 'Atroos comunicazione website e dm',
    pm: 'Greta Alberghini',
  },
  {
    type: 'Progetto',
    client: 'Arsenalia FR',
    order: 'Kering (Arsenalia FR) Netiquette 2025',
    pm: 'Giulia Trincanato',
  },
  {
    type: 'Pitch',
    client: 'Pettenon Cosmetics',
    order: 'Pettenon Pitch 80',
    pm: 'Filippo Stocco',
  },
  {
    type: 'Progetto',
    client: 'SNCF',
    order: 'SNCF UX UI design',
    pm: 'Luca Dalla Costa',
  },
  {
    type: 'Progetto',
    client: 'Calligaris',
    order: 'Calligaris Pink Project 2025',
    pm: 'Francesca Pavan',
  },
  {
    type: 'Progetto',
    client: 'Gefran Spa',
    order: 'Gefran piattaforma G Mation',
    pm: 'Francesca Pavan',
  },
  {
    type: 'Progetto',
    client: 'Kìron',
    order: 'Kiron manut tecnica DTC25',
    pm: 'Federica Tommasi',
  },
  {
    type: 'Progetto',
    client: 'VGI',
    order: 'VGI migrazione CSP su container AWS',
    pm: 'Roberto Cosma',
  },
];

export async function seedProjects() {
  try {
    console.log('🏗️ Starting projects table seeding...');

    // Puliamo la tabella prima di inserire
    await db.delete(projects);
    console.log('🧹 Cleared existing data from projects table');

    // Inseriamo i nuovi dati
    await db.insert(projects).values(projectsData);

    console.log('✅ Successfully seeded PROJECTS table!');
    console.log(`📁 Projects inserted: ${projectsData.length}`);

    // Verifichiamo l'inserimento
    const insertedProjects = await db.select().from(projects);
    console.log('\n📋 Inserted projects:');
    insertedProjects.forEach((item) => {
      console.log(
        `   ${item.type} | ${item.client} | ${item.order} | ${item.pm}`
      );
    });
  } catch (error) {
    console.error('❌ Error seeding PROJECTS table:', error);
    if (error instanceof Error) {
      console.error('Error details:', {
        message: error.message,
        stack: error.stack,
      });
    }
    process.exit(1);
  }
}

seedProjects();
